### ISSUE TITLE
FILE <-> GPU optimization

### ISSUE THREAD

**Issue by pr2718** [cgi-estonia-space/asar-focus#11]
The chain from file -> CPU -> GPU and back is currently sub optimal.

Potential optimizations:

Reading:
- FBAQ decoding on GPU to minimize Host->Device transfer time
- parallelize host to device transfers, e.g send data to gpu while parts of the file is read

Writing:
- complex float32 to big endian complex int16 on GPU

**Comment by kautlenbachs** [comment]
int16 output data could be written to reusable memory area. (d_workspace reuse)
