### ISSUE TITLE
Broken datasets detection

### ISSUE THREAD

**Issue by pr2718** [cgi-estonia-space/asar-focus#12]
Some datasets are known to be incorrect, some issues can be alleviated, some can not be and the program should gracefully exit.

At the moment, asar-focus does very little error detection and correction.

**Comment by kautlenbachs** [comment]
Connected to https://github.com/cgi-estonia-space/asar-focus/issues/16

**Comment by kautlenbachs** [comment]
The broken datasets did not result in crashes of the processor. The logs correctly pinpoint the cause of the cancellation of further focussing. The TDS that were verified are: 20, 21, 23, 26, 27, 28 ,29 ,30.
