### ISSUE TITLE
Multilooked product generation support

### ISSUE THREAD

**Issue by pr2718** [cgi-estonia-space/asar-focus#4]
Current version just support IM -> IMS.

Add support for example IMP - multilooked and ground range product.

**Comment by pr2718** [comment]
IMM mode uses SPECAN, this won't be in the 2.0 release.

**Comment by kautlenbachs** [comment]
Currently unsolved issues that are blocking the release:
- antenna elevation gain correction
- range spreading loss correction
- spacing resampling
